version: "3.7"
services:
  kong-database:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER=kong
      POSTGRES_DB=kong
      POSTGRES_PASSWORD=kongpass
    networks: 
      - kong-net

  kong-gateway:
    image: kong/kong-gateway:2.8.1.1-alpine
    environment:
      KONG_DATABASE=postgres
      KONG_PG_HOST=kong-database
      KONG_PG_PASSWORD=kongpass
      KONG_PASSWORD=test
      KONG_PG_USER=kong
      KONG_PG_PASSWORD=kongpass
      KONG_PROXY_ACCESS_LOG=/dev/stdout
      KONG_ADMIN_ACCESS_LOG=/dev/stdout
      KONG_PROXY_ERROR_LOG=/dev/stderr
      KONG_ADMIN_ERROR_LOG=/dev/stderr
      KONG_ADMIN_LISTEN=0.0.0.0:8001
      KONG_ADMIN_GUI_URL=http://0.0.0.0:8002
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    command: kong migrations bootstrap
    networks: 
      - kong-net
    depends_on:
      - kong-database
    
networks:
  kong-net: {}
